# Generated by Django 5.1.5 on 2025-02-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
